apiVersion: v1
kind: Service
metadata:
  labels:
    app: reverse-words
  name: reverse-words
spec:
  type: NodePort
  selector:
    app: reverse-words
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
