apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: reversewords-region-app-subscription
  namespace: reverse-words-region
  labels:
    app: reversewords-region-app
  annotations:
    apps.open-cluster-management.io/git-path: apps/reversewords/
    apps.open-cluster-management.io/git-branch: prod
spec:
  channel: open-cluster-management/acm-app-lifecycle-blog
  placement:
    placementRef:
      kind: PlacementRule
      name: eu-region-clusters

